runtime: python38

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /favicon\.ico
    secure: always
    static_files: static/images/favicon.ico
    upload: static/images/favicon\.ico
