runtime: python38

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
