name: On push

on: [ push , workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret
        run: gpg --quiet --batch --decrypt --passphrase="${{ secrets.GPG_SECRET_PASSPHRASE }}" --output=.env .env.gpg
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -r requirements.txt
      - id: lint
        name: Lint with flake8
        run: |
          flake8 *.py
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GAE_SECRET_KEY }}
          export_default_credentials: true
      - id: test
        name: Test with pytest
        run: |
          pytest . -vv --ignore-glob="venv/**/*" --durations=0 --cov --cov-branch --cov-report=xml
          bash <(curl -s https://codecov.io/bash)
      - id: deploy
        name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Check Deployed URL
        run: curl "${{ steps.deploy.outputs.url }}"
